import data
# Questions:
#   Question 1: Rate 1-7 how much representation you feel is reflected from Cal Poly faculty & staff
#   Question 2: Rate 1-7 your comfortability in a classroom setting based on the demographics of your classmates
#   Question 3: Rate 1-7 how supported you feel as a Black student in Cal Poly for resources
#   Question 4: Rate 1-7 how much you agree with the following statement: "I see students like me walking about campus"
#   Question 5: Rate 1-7 how much you agree with the following statement: "I feel safe as a Black student at Cal Poly"
#   Question 6: Rate 1-7, 1 being least, 7 being most, how often you face discrimination: hate speech, open prejudices, etc. at Cal Poly
# Freshmen: 10
# Sophomores: 10
# Junior: 14
# Senior: 6

questions_data = {
    "Question 1": {
#   Question 1: Rate 1-7 how much representation you feel is reflected from Cal Poly faculty & staff
        "Freshman":  {1: 3,
                      2: 4,
                      3: 3,
                      4: 0,
                      5: 0,
                      6: 0,
                      7: 0},
        "Sophomore": {1: 1,
                      2: 5,
                      3: 3,
                      4: 1,
                      5: 0,
                      6: 0,
                      7: 0},
        "Junior":    {1: 4,
                      2: 4,
                      3: 4,
                      4: 2,
                      5: 0,
                      6: 0,
                      7: 0},
        "Senior":    {1: 2,
                      2: 2,
                      3: 1,
                      4: 1,
                      5: 0,
                      6: 0,
                      7: 0}
    },
    "Question 2": {
#   Question 2: Rate 1-7 your comfortability in a classroom setting based on the demographics of your classmates
        "Freshman":  {1: 1,
                      2: 2,
                      3: 2,
                      4: 2,
                      5: 3,
                      6: 0,
                      7: 0},
        "Sophomore": {1: 2,
                      2: 1,
                      3: 4,
                      4: 3,
                      5: 0,
                      6: 0,
                      7: 0},
        "Junior":    {1: 0,
                      2: 2,
                      3: 5,
                      4: 5,
                      5: 2,
                      6: 0,
                      7: 0},
        "Senior":    {1: 0,
                      2: 1,
                      3: 2,
                      4: 2,
                      5: 3,
                      6: 0,
                      7: 0}
    },
    "Question 3": {
#   Question 3: Rate 1-7 how supported you feel as a Black student in Cal Poly for resources
        "Freshman":  {1: 0,
                      2: 1,
                      3: 1,
                      4: 2,
                      5: 5,
                      6: 1,
                      7: 0},
        "Sophomore": {1: 0,
                      2: 1,
                      3: 1,
                      4: 3,
                      5: 4,
                      6: 2,
                      7: 0},
        "Junior":    {1: 0,
                      2: 1,
                      3: 1,
                      4: 5,
                      5: 5,
                      6: 1,
                      7: 1},
        "Senior":    {1: 0,
                      2: 2,
                      3: 2,
                      4: 2,
                      5: 1,
                      6: 0,
                      7: 0}
    },
    "Question 4": {
#   Question 4: Rate 1-7 how much you agree with the following statement: "I see students like me walking about campus"
        "Freshman":  {1: 3,
                      2: 2,
                      3: 3,
                      4: 1,
                      5: 1,
                      6: 0,
                      7: 0},
        "Sophomore": {1: 2,
                      2: 5,
                      3: 2,
                      4: 3,
                      5: 0,
                      6: 0,
                      7: 0},
        "Junior":    {1: 3,
                      2: 5,
                      3: 4,
                      4: 1,
                      5: 0,
                      6: 0,
                      7: 0},
        "Senior":    {1: 0,
                      2: 2,
                      3: 2,
                      4: 2,
                      5: 1,
                      6: 0,
                      7: 0}
    },
    "Question 5": {
#   Question 5: Rate 1-7 how much you agree with the following statement: "I feel safe as a Black student at Cal Poly"
        "Freshman":  {1: 1,
                      2: 1,
                      3: 3,
                      4: 4,
                      5: 1,
                      6: 0,
                      7: 0},
        "Sophomore": {1: 3,
                      2: 4,
                      3: 2,
                      4: 1,
                      5: 0,
                      6: 0,
                      7: 0},
        "Junior":    {1: 1,
                      2: 6,
                      3: 4,
                      4: 2,
                      5: 0,
                      6: 1,
                      7: 0},
        "Senior":    {1: 0,
                      2: 1,
                      3: 3,
                      4: 1,
                      5: 1,
                      6: 0,
                      7: 0}
    },
    "Question 6": {
#   Question 6: Rate 1-7, 1 being least, 7 being most, how often you face discrimination: hate speech, open prejudices, etc. at Cal Poly
        "Freshman":  {1: 0,
                      2: 0,
                      3: 1,
                      4: 3,
                      5: 5,
                      6: 1,
                      7: 0},
        "Sophomore": {1: 0,
                      2: 1,
                      3: 2,
                      4: 3,
                      5: 3,
                      6: 1,
                      7: 0},
        "Junior":    {1: 1,
                      2: 1,
                      3: 1,
                      4: 5,
                      5: 5,
                      6: 1,
                      7: 0},
        "Senior":    {1: 0,
                      2: 1,
                      3: 2,
                      4: 3,
                      5: 1,
                      6: 0,
                      7: 0}
    }
}