DemographicData= {2015:{"HISPANIC/LATINO":15.6,
                        "AFRICAN AMERICAN": 0.8,
                        "NATIVE AMERICAN": 0.1,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.1,
                        "ASIAN AMERICAN": 12.2,
                        "MULTI-RACIAL": 6.9,
                        "WHITE": 57.3,
                        "NON-RESIDENT ALIEN": 2.1,
                        "UNKNOWN":4.8},

                  2016:{"HISPANIC/LATINO": 16,
                        "AFRICAN AMERICAN": 0.7,
                        "NATIVE AMERICAN": 0.1,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.1,
                        "ASIAN AMERICAN": 12.6,
                        "MULTI-RACIAL": 7.1,
                        "WHITE": 56.4,
                        "NON-RESIDENT ALIEN": 2.2,
                        "UNKNOWN":4.7},

                  2017:{"HISPANIC/LATINO": 16.8,
                        "AFRICAN AMERICAN": 0.8,
                        "NATIVE AMERICAN": 0.1,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.2,
                        "ASIAN AMERICAN": 12.9,
                        "MULTI-RACIAL": 7.6,
                        "WHITE": 54.7,
                        "NON-RESIDENT ALIEN": 2.2,
                        "UNKNOWN":4.8},

                  2018:{"HISPANIC/LATINO": 17.03,
                        "AFRICAN AMERICAN": 0.78,
                        "NATIVE AMERICAN": 0.14,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.1,
                        "ASIAN AMERICAN": 13.08,
                        "MULTI-RACIAL": 7.63,
                        "WHITE": 54.60,
                        "NON-RESIDENT ALIEN": 2.34,
                        "UNKNOWN":4.40},

                  2019:{"HISPANIC/LATINO": 17.49,
                        "AFRICAN AMERICAN": 0.84,
                        "NATIVE AMERICAN": 0.14,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.0,
                        "ASIAN AMERICAN": 13.46,
                        "MULTI-RACIAL": 7.72,
                        "WHITE": 53.98,
                        "NON-RESIDENT ALIEN": 2.42,
                        "UNKNOWN": 3.96},

                  2020:{"HISPANIC/LATINO": 18.33,
                        "AFRICAN AMERICAN": 0.77,
                        "NATIVE AMERICAN": 0.12,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.0,
                        "ASIAN AMERICAN": 13.33,
                        "MULTI-RACIAL": 7.73,
                        "WHITE": 54.04,
                        "NON-RESIDENT ALIEN": 2.14,
                        "UNKNOWN":3.54},

                  2021:{"HISPANIC/LATINO": 19.39,
                        "AFRICAN AMERICAN": 0.72,
                        "NATIVE AMERICAN": 0.12,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.23,
                        "ASIAN AMERICAN": 13.44,
                        "MULTI-RACIAL": 7.51,
                        "WHITE": 53.2,
                        "NON-RESIDENT ALIEN": 2.2,
                        "UNKNOWN":3.18},
                  
                  2022:{"HISPANIC/LATINO": 21.09,
                        "AFRICAN AMERICAN": 0.73,
                        "NATIVE AMERICAN": 0.1,
                        "HAWAIIAN/PACIFIC ISLANDER": 0.26,
                        "ASIAN AMERICAN": 13.9,
                        "MULTI-RACIAL": 7.72,
                        "WHITE": 51.41,
                        "NON-RESIDENT ALIEN": 1.96,
                        "UNKNOWN":2.84}}